#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
#!/bin/bash

# To update the version shipped in this quickstart, bump this variable:
#
install_version="3.0.0+"
upstream_version=30

# Download and install WordPress

install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${install_version}

# Used in this script only
current_version_dir=${OPENSHIFT_DATA_DIR}current

#
# If WordPress is already installed in the current gear, there
# is nothing to build :-)
#
[ -d "${current_version_dir}" ] && exit 0

mkdir -p $install_dir

pushd ${install_dir} >/dev/null
curl -o moodle-latest-${upstream_version}.tgz -kLs https://download.moodle.org/download.php/direct/stable${upstream_version}/moodle-latest-${upstream_version}.tgz

# Install Moodle
#
tar --strip-components=1 -xzf moodle-latest-${upstream_version}.tgz
rm -rf moodle-latest-${upstream_version}.tgz
echo $install_version > ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version

popd >/dev/null
